# Generated by Django 4.1.5 on 2023-01-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('serialNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registredQt', models.IntegerField()),
                ('livedQt', models.IntegerField()),
                ('totalArea', models.FloatField()),
                ('personalAccount', models.IntegerField()),
                ('serialNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartment')),
            ],
        ),
    ]
