# Generated by Django 4.1.4 on 2023-02-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentdetail',
            name='account_number',
            field=models.CharField(default=222, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ApartmentOption',
        ),
    ]
