# Generated by Django 4.1.4 on 2023-02-15 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_water_previous', models.IntegerField(default=0)),
                ('hot_water_current', models.IntegerField(default=0)),
                ('hot_water_value', models.IntegerField(default=0)),
                ('cold_water_previous', models.IntegerField(default=0)),
                ('cold_water_current', models.IntegerField(default=0)),
                ('cold_water_value', models.IntegerField(default=0)),
                ('electricity_previous', models.IntegerField(default=0)),
                ('electricity_current', models.IntegerField(default=0)),
                ('electricity_value', models.IntegerField(default=0)),
                ('wastewater_value', models.IntegerField(default=0)),
                ('serialNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartment')),
            ],
        ),
    ]
