# Generated by Django 4.1.4 on 2023-02-15 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_apartmentcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_odn', models.FloatField()),
                ('money_deposited', models.FloatField()),
                ('fine', models.FloatField()),
                ('serialNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartment')),
            ],
        ),
    ]
