# Generated by Django 4.1.4 on 2023-02-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_apartmentcharges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartmentCharges',
            new_name='ApartmentCharge',
        ),
    ]
