# Generated by Django 4.1.4 on 2023-03-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
        ('main', '0004_alter_settings_options_alter_tariff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentdetail',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tariff.tariff'),
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
    ]
