# Generated by Django 4.1.4 on 2023-02-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_apartmentcharges_apartmentcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cold_water_meter', models.BooleanField()),
                ('is_hot_water_meter', models.BooleanField()),
                ('is_first_floor', models.BooleanField()),
                ('is_absence_registred', models.BooleanField()),
                ('serialNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartment')),
            ],
        ),
    ]
