# Generated by Django 4.1.4 on 2023-02-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentdetail',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tariff'),
        ),
    ]
