# Generated by Django 4.1.4 on 2023-02-18 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_apartmentdetail_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.FloatField(blank=True, null=True)),
                ('electricity_odn', models.FloatField(blank=True, null=True)),
                ('lift', models.FloatField(blank=True, null=True)),
                ('maintenance_full', models.FloatField(blank=True, null=True)),
                ('solid_waste', models.FloatField(blank=True, null=True)),
                ('electricity', models.FloatField(blank=True, null=True)),
                ('heating', models.FloatField(blank=True, null=True)),
                ('heating_rub', models.FloatField(blank=True, null=True)),
                ('hot_water', models.FloatField(blank=True, null=True)),
                ('cold_water', models.FloatField(blank=True, null=True)),
                ('sewage', models.FloatField(blank=True, null=True)),
                ('maintenance_total', models.FloatField(blank=True, null=True)),
                ('accrued_expenses', models.FloatField(blank=True, null=True)),
                ('recalculation', models.FloatField(blank=True, null=True)),
                ('balance_start', models.FloatField(blank=True, null=True)),
                ('balance_end', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('fine', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('serialNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartment')),
            ],
        ),
    ]
