# Generated by Django 4.1.4 on 2023-02-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_apartmentfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentcharge',
            name='recalculation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
