# Generated by Django 4.1.4 on 2023-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_apartmentfee_cold_water_odn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='cold_water_odn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='hot_water_odn_over_norm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
