# Generated by Django 4.1.4 on 2023-02-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tariff_cold_water_odn_tariff_hot_water_odn_over_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentcharge',
            name='balance_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
