# Generated by Django 4.1.4 on 2023-02-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_apartmentcharge_balance_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=200)),
                ('month_to_pay', models.CharField(max_length=200)),
                ('month_to_date', models.CharField(max_length=200)),
                ('bill', models.CharField(max_length=200)),
                ('pay_up_to', models.CharField(max_length=200)),
            ],
        ),
    ]
