# Generated by Django 4.1.4 on 2023-02-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentfee',
            name='sewage_odn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='sewage_odn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
