# Generated by Django 4.1.4 on 2023-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_apartmentfee_sewage_odn_tariff_sewage_odn'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentcharge',
            name='recalculation_cold_water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentcharge',
            name='recalculation_electricity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentcharge',
            name='recalculation_heating_rub',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentcharge',
            name='recalculation_hot_water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentcharge',
            name='recalculation_sewage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentcharge',
            name='recalculation_solid_waste',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
