# Generated by Django 4.1.4 on 2023-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('maintenance', models.FloatField(blank=True, null=True)),
                ('heating', models.FloatField(blank=True, null=True)),
                ('heating_rub', models.FloatField(blank=True, null=True)),
                ('hot_water', models.FloatField(blank=True, null=True)),
                ('hot_water_odn', models.FloatField(blank=True, null=True)),
                ('cold_water', models.FloatField(blank=True, null=True)),
                ('cold_water_odn', models.FloatField(blank=True, null=True)),
                ('sewage', models.FloatField(blank=True, null=True)),
                ('sewage_odn', models.FloatField(blank=True, null=True)),
                ('solid_waste', models.FloatField(blank=True, null=True)),
                ('electricity', models.FloatField(blank=True, null=True)),
                ('lift', models.FloatField(blank=True, null=True)),
                ('electricity_odn', models.FloatField(blank=True, null=True)),
                ('capital_repair', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'tariff',
                'verbose_name_plural': 'tariffs',
            },
        ),
    ]
