# Generated by Django 4.1.7 on 2023-06-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='multiplying_factor',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
